[2025-05-08T17:34:16.824+0000] {processor.py:161} INFO - Started process (PID=164) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:34:16.825+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:34:16.828+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:34:16.828+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:34:16.841+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:34:16.840+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:34:16.841+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:34:16.854+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.037 seconds
[2025-05-08T17:34:47.197+0000] {processor.py:161} INFO - Started process (PID=169) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:34:47.198+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:34:47.201+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:34:47.200+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:34:47.229+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:34:47.226+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:34:47.229+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:34:47.253+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.065 seconds
[2025-05-08T17:35:17.507+0000] {processor.py:161} INFO - Started process (PID=174) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:35:17.508+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:35:17.511+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:35:17.510+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:35:17.522+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:35:17.520+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:35:17.522+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:35:17.548+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.047 seconds
[2025-05-08T17:35:47.821+0000] {processor.py:161} INFO - Started process (PID=179) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:35:47.823+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:35:47.826+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:35:47.825+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:35:47.846+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:35:47.844+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:35:47.846+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:35:47.864+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.053 seconds
[2025-05-08T17:36:18.227+0000] {processor.py:161} INFO - Started process (PID=184) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:36:18.228+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:36:18.231+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:36:18.230+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:36:18.276+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:36:18.268+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:36:18.276+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:36:18.307+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.089 seconds
[2025-05-08T17:36:48.592+0000] {processor.py:161} INFO - Started process (PID=189) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:36:48.593+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:36:48.597+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:36:48.597+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:36:48.609+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:36:48.607+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:36:48.609+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:36:48.627+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.050 seconds
[2025-05-08T17:37:18.952+0000] {processor.py:161} INFO - Started process (PID=194) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:37:18.953+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:37:18.956+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:37:18.955+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:37:18.968+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:37:18.967+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:37:18.969+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:37:18.986+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.041 seconds
[2025-05-08T17:37:49.345+0000] {processor.py:161} INFO - Started process (PID=199) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:37:49.347+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:37:49.352+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:37:49.351+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:37:49.364+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:37:49.362+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:37:49.364+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:37:49.382+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.057 seconds
[2025-05-08T17:38:19.837+0000] {processor.py:161} INFO - Started process (PID=204) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:38:19.838+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:38:19.842+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:38:19.841+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:38:19.857+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:38:19.855+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:38:19.857+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:38:19.874+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.050 seconds
[2025-05-08T17:38:50.242+0000] {processor.py:161} INFO - Started process (PID=209) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:38:50.243+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:38:50.247+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:38:50.246+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:38:50.260+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:38:50.258+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:38:50.260+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:38:50.278+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.045 seconds
[2025-05-08T17:39:35.115+0000] {processor.py:161} INFO - Started process (PID=164) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:39:35.117+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:39:35.119+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:39:35.119+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:39:35.130+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:39:35.129+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:39:35.130+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:39:35.145+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.034 seconds
[2025-05-08T17:40:05.657+0000] {processor.py:161} INFO - Started process (PID=169) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:40:05.659+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:40:05.663+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:40:05.662+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:40:05.684+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:40:05.681+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:40:05.688+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:40:05.732+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.091 seconds
[2025-05-08T17:40:36.000+0000] {processor.py:161} INFO - Started process (PID=174) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:40:36.002+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:40:36.005+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:40:36.004+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:40:36.019+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:40:36.017+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:40:36.020+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:40:36.043+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.067 seconds
[2025-05-08T17:41:06.376+0000] {processor.py:161} INFO - Started process (PID=179) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:41:06.378+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:41:06.381+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:41:06.381+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:41:06.397+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:41:06.395+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:41:06.398+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:41:06.426+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.064 seconds
[2025-05-08T17:41:36.793+0000] {processor.py:161} INFO - Started process (PID=184) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:41:36.794+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:41:36.798+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:41:36.798+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:41:36.812+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:41:36.810+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:41:36.813+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:41:36.830+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.050 seconds
[2025-05-08T17:42:07.224+0000] {processor.py:161} INFO - Started process (PID=189) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:42:07.225+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:42:07.230+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:42:07.229+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:42:07.246+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:42:07.244+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:42:07.247+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:42:07.266+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.064 seconds
[2025-05-08T17:42:37.570+0000] {processor.py:161} INFO - Started process (PID=194) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:42:37.571+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:42:37.573+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:42:37.573+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:42:37.584+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:42:37.582+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:42:37.585+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:42:37.601+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.044 seconds
[2025-05-08T17:43:08.012+0000] {processor.py:161} INFO - Started process (PID=199) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:43:08.013+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:43:08.017+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:43:08.016+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:43:08.034+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:43:08.031+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:43:08.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:43:08.060+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.059 seconds
[2025-05-08T17:43:52.837+0000] {processor.py:161} INFO - Started process (PID=163) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:43:52.839+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:43:52.844+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:43:52.842+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:43:52.857+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:43:52.856+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:43:52.858+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:43:52.870+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.038 seconds
[2025-05-08T17:44:23.333+0000] {processor.py:161} INFO - Started process (PID=168) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:44:23.335+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:44:23.339+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:44:23.339+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:44:23.363+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:44:23.358+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:44:23.364+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:44:23.409+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.093 seconds
[2025-05-08T17:44:53.746+0000] {processor.py:161} INFO - Started process (PID=173) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:44:53.747+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:44:53.749+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:44:53.749+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:44:53.758+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:44:53.757+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:44:53.759+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:44:53.777+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.046 seconds
[2025-05-08T17:45:24.090+0000] {processor.py:161} INFO - Started process (PID=178) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:45:24.091+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:45:24.094+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:45:24.094+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:45:24.107+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:45:24.105+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:45:24.108+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:45:24.124+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.046 seconds
[2025-05-08T17:45:54.434+0000] {processor.py:161} INFO - Started process (PID=183) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:45:54.439+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:45:54.451+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:45:54.450+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:45:54.477+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:45:54.475+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:45:54.477+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:45:54.495+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.070 seconds
[2025-05-08T17:46:24.791+0000] {processor.py:161} INFO - Started process (PID=188) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:46:24.798+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:46:24.809+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:46:24.808+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:46:24.838+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:46:24.836+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:46:24.839+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:46:24.860+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.080 seconds
[2025-05-08T17:46:55.231+0000] {processor.py:161} INFO - Started process (PID=193) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:46:55.232+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:46:55.235+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:46:55.234+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:46:55.247+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:46:55.245+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:46:55.247+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:46:55.265+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.050 seconds
[2025-05-08T17:47:25.605+0000] {processor.py:161} INFO - Started process (PID=198) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:47:25.607+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:47:25.610+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:47:25.610+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:47:25.647+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:47:25.644+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:47:25.648+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:47:25.669+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.076 seconds
[2025-05-08T17:47:55.941+0000] {processor.py:161} INFO - Started process (PID=203) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:47:55.942+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:47:55.945+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:47:55.944+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:47:55.955+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:47:55.954+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:47:55.956+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:47:55.970+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.037 seconds
[2025-05-08T17:48:26.324+0000] {processor.py:161} INFO - Started process (PID=208) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:48:26.325+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:48:26.329+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:48:26.328+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:48:26.343+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:48:26.341+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:48:26.343+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:48:26.361+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.052 seconds
[2025-05-08T17:48:57.035+0000] {processor.py:161} INFO - Started process (PID=213) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:48:57.037+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:48:57.040+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:48:57.040+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:48:57.058+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:48:57.055+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:48:57.058+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:48:57.104+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.124 seconds
[2025-05-08T17:53:19.302+0000] {processor.py:161} INFO - Started process (PID=220) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:53:19.307+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:53:19.314+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:53:19.313+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:53:19.358+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:53:19.349+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:53:19.360+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:53:19.416+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.167 seconds
[2025-05-08T17:53:49.689+0000] {processor.py:161} INFO - Started process (PID=225) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:53:49.691+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:53:49.695+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:53:49.694+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:53:49.711+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:53:49.709+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:53:49.711+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:53:49.736+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.056 seconds
[2025-05-08T17:54:20.237+0000] {processor.py:161} INFO - Started process (PID=230) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:54:20.240+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:54:20.243+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:54:20.243+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:54:20.275+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:54:20.270+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:54:20.276+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:54:20.321+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.105 seconds
[2025-05-08T17:54:50.691+0000] {processor.py:161} INFO - Started process (PID=235) to work on /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:54:50.694+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/crypto_tracker_dag.py for tasks to queue
[2025-05-08T17:54:50.698+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:54:50.698+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:54:50.714+0000] {logging_mixin.py:188} INFO - [2025-05-08T17:54:50.712+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/crypto_tracker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/crypto_tracker_dag.py", line 14, in <module>
    BASE_DIR       = Path(_file_).resolve().parent.parent
                          ^^^^^^
NameError: name '_file_' is not defined
[2025-05-08T17:54:50.714+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/crypto_tracker_dag.py
[2025-05-08T17:54:50.737+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/crypto_tracker_dag.py took 0.058 seconds
